# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - drumbeat-egrhd72feuspa(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Build with dotnet
      run: dotnet build src/ --configuration Release

    - name: dotnet publish
      run: dotnet publish src/ -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: drumbeat-ai-egrhd72feuspa
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_07AF881664E14A658F41C5A0298854B8 }}
        package: ${{env.DOTNET_ROOT}}/myapp

